insert into student values(10001,'Ranga', 'E1234567');
insert into student values(10002,'Ravi', 'A1234568');

-- this is the create table DML
-- create table student (id int8 generated by default as identity,name varchar(255), long_text text, primary key (id));
